FORMAT: 1A

# Axentro API
The following information gives an overview of the Axentro API

## Overview

The Axentro blockchain platform is an original proof of work blockchain that blends slow blocks and fast blocks into a single chain to provide a range of functionality. Axentro aims to provide a platform for building decentralised ap