## Group Node

# /node

## GET

Show information about the current node
    
+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": 
                {
                  "id": "0bd4b62baa97bf1ac608ae311d41c0b6",
                  "host": "testnet.axentro.io",
                  "port": 3000,
                  "ssl": false,
                  "type": "testnet",
                  "is_private": false,
                  "address": ""
                }
            }

        
## node/id [GET /node/{id}]

Show information about the specified node id

+ Parameters

    + id (number) - The node id
    
+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": 
                {
                  "id": "0bd4b62baa97bf1ac608ae311d41c0b6",
                  "host": "testnet.axentro.io",
                  "port": 3000,
                  "ssl": false,
                  "type": "testnet",
                  "is_private": false,
      